INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('AFG', 'https://www.mappi.net/country/img/afghanistan/flag_Afghanistan.svg.png', 'Afghanistan', 'Afghanistan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ALA', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Aland', 'Aland Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ALB', 'https://mappi.net/country/img/albania/flag_albania.png', 'Albanie', 'Albania');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('DZA', 'https://mappi.net/country/img/algeria/flag_algeria.png', 'Algérie', 'Algeria');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ASM', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Samoa américaines', 'American Samoa');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('AND', 'https://mappi.net/country/img/andorra/flag_andorra.png', 'Andorre', 'Andorra');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('AGO', 'https://mappi.net/country/img/angola/flag_angola.png', 'Angola', 'Angola');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('AIA', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Anguilla', 'Anguilla');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ATA', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Antarctique', 'Antarctica');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ATG', 'https://mappi.net/country/img/antigua_and_barbuda/flag_antigua_and_barbuda.png', 'Antigua-et-Barbuda', 'Antigua and Barbuda');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ARG', 'https://mappi.net/country/img/argentina/flag_argentina.png', 'Argentine', 'Argentina');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ARM', 'https://mappi.net/country/img/armenia/flag_armenia.png', 'Arménie', 'Armenia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ABW', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Aruba', 'Aruba');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('AUS', 'https://mappi.net/country/img/australia/flag_australia.png', 'Australie', 'Australia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('AUT', 'https://mappi.net/country/img/austria/flag_austria.png', 'Autriche', 'Austria');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('AZE', 'https://mappi.net/country/img/azerbaijan/flag_azerbaijan.png', 'Azerbaïdjan', 'Azerbaijan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BHS', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Bahamas', 'Bahamas');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BHR', 'https://mappi.net/country/img/bahrain/flag_bahrain.png', 'Bahreïn', 'Bahrain');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BGD', 'https://mappi.net/country/img/bangladesh/flag_bangladesh.png', 'Bangladesh', 'Bangladesh');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BRB', 'https://mappi.net/country/img/barbados/flag_barbados.png', 'Barbades', 'Barbados');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BLR', 'https://mappi.net/country/img/belarus/flag_belarus.png', 'Biélorussie', 'Belarus');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BEL', 'https://mappi.net/country/img/belgium/flag_belgium.png', 'Belgique', 'Belgium');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BLZ', 'https://mappi.net/country/img/belize/flag_belize.png', 'Belize', 'Belize');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BEN', 'https://mappi.net/country/img/benin/flag_benin.png', 'Bénin', 'Benin');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BMU', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Bermudes', 'Bermuda');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BTN', 'https://mappi.net/country/img/bhutan/flag_bhutan.png', 'Bhoutan', 'Bhutan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BOL', 'https://mappi.net/country/img/bolivia/flag_bolivia.png', 'Bolivie', 'Bolivia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BES', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Saba, Saint-Eustache et Bonaire', 'Bonaire, Saint Eustatius and Saba');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BIH', 'https://mappi.net/country/img/bosnia_and_herzegovina/flag_bosnia_and_herzegovina.png', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BWA', 'https://mappi.net/country/img/botswana/flag_botswana.png', 'Botswana', 'Botswana');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BVT', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Île Bouvet', 'Bouvet Island');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BRA', 'https://mappi.net/country/img/brazil/flag_brazil.png', 'Brésil', 'Brazil');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('IOT', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Territoire Britannique de l''Océan Indien', 'British Indian Ocean Territory');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('VGB', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Vierges britanniques', 'British Virgin Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BRN', 'https://mappi.net/country/img/brunei/flag_brunei.png', 'Brunei', 'Brunei');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BGR', 'https://mappi.net/country/img/bulgaria/flag_bulgaria.png', 'Bulgarie', 'Bulgaria');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BFA', 'https://mappi.net/country/img/burkina/flag_burkina.png', 'Burkina Faso', 'Burkina Faso');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BDI', 'https://mappi.net/country/img/burundi/flag_burundi.png', 'Burundi', 'Burundi');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CPV', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Cap-Vert', 'Cabo Verde');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KHM', 'https://mappi.net/country/img/cambodia/flag_cambodia.png', 'Cambodge', 'Cambodia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CMR', 'https://mappi.net/country/img/cameroon/flag_cameroon.png', 'Cameroun', 'Cameroon');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CAN', 'https://mappi.net/country/img/canada/flag_canada.png', 'Canada', 'Canada');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CYM', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Caïmans', 'Cayman Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CAF', 'https://mappi.net/country/img/central_african_republic/flag_central_african_republic.png', 'République centrafricaine', 'Central African Republic');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TCD', 'https://mappi.net/country/img/chad/flag_chad.png', 'Tchad', 'Chad');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CHL', 'https://mappi.net/country/img/chile/flag_chile.png', 'Chili', 'Chile');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CHN', 'https://mappi.net/country/img/china/flag_china.png', 'Chine', 'China');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CXR', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Christmas', 'Christmas Island');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CCK', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Cocos', 'Cocos Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('COL', 'https://mappi.net/country/img/colombia/flag_colombia.png', 'Colombie', 'Colombia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('COM', 'https://mappi.net/country/img/comoros/flag_comoros.png', 'Comores', 'Comoros');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('COK', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Cook', 'Cook Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CRI', 'https://mappi.net/country/img/costa_rica/flag_costa_rica.png', 'Costa Rica', 'Costa Rica');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('HRV', 'https://mappi.net/country/img/croatia/flag_croatia.png', 'Croatie', 'Croatia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CUB', 'https://mappi.net/country/img/cuba/flag_cuba.png', 'Cuba', 'Cuba');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CUW', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Curacao', 'Curacao');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CYP', 'https://mappi.net/country/img/cyprus/flag_cyprus.png', 'Chypre', 'Cyprus');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CZE', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Czechia', 'Czechia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('COD', 'https://mappi.net/country/img/democratic_republic_of_the_congo/flag_democratic_republic_of_the_congo.png', 'République démocratique du Congo', 'Democratic Republic of the Congo');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('DNK', 'https://mappi.net/country/img/denmark/flag_denmark.png', 'Danemark', 'Denmark');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('DJI', 'https://mappi.net/country/img/djibouti/flag_djibouti.png', 'Djibouti', 'Djibouti');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('DMA', 'https://mappi.net/country/img/dominica/flag_dominica.png', 'Dominique', 'Dominica');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('DOM', 'https://mappi.net/country/img/dominican_republic/flag_dominican_republic.png', 'République Dominicaine', 'Dominican Republic');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ECU', 'https://mappi.net/country/img/ecuador/flag_ecuador.png', 'Équateur', 'Ecuador');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('EGY', 'https://mappi.net/country/img/egypt/flag_egypt.png', 'Égypte', 'Egypt');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SLV', 'https://mappi.net/country/img/el_salvador/flag_el_salvador.png', 'Le Salvador', 'El Salvador');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GNQ', 'https://mappi.net/country/img/equatorial_guinea/flag_equatorial_guinea.png', 'Guinée équatoriale', 'Equatorial Guinea');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ERI', 'https://mappi.net/country/img/eritrea/flag_eritrea.png', 'Érythrée', 'Eritrea');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('EST', 'https://mappi.net/country/img/estonia/flag_estonia.png', 'Estonie', 'Estonia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SWZ', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Eswatini', 'Eswatini');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ETH', 'https://mappi.net/country/img/ethiopia/flag_ethiopia.png', 'Éthiopie', 'Ethiopia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('FLK', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Falkland', 'Falkland Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('FRO', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Féroé', 'Faroe Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('FJI', 'https://mappi.net/country/img/fiji/flag_fiji.png', 'Fiji', 'Fiji');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('FIN', 'https://mappi.net/country/img/finland/flag_finland.png', 'Finlande', 'Finland');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('FRA', 'https://mappi.net/country/img/france/flag_france.png', 'France', 'France');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GUF', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Guyane francaise', 'French Guiana');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PYF', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Polynésie francaise', 'French Polynesia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ATF', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Terres australes et antarctiques francaises', 'French Southern Territories');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GAB', 'https://mappi.net/country/img/gabon/flag_gabon.png', 'Gabon', 'Gabon');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GMB', 'https://mappi.net/country/img/gambia/flag_gambia.png', 'Gambie', 'Gambia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GEO', 'https://mappi.net/country/img/georgia/flag_georgia.png', 'État de Géorgie', 'Georgia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('DEU', 'https://mappi.net/country/img/germany/flag_germany.png', 'Allemagne', 'Germany');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GHA', 'https://mappi.net/country/img/ghana/flag_ghana.png', 'Ghana', 'Ghana');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GIB', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Gribraltar', 'Gibraltar');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GRC', 'https://mappi.net/country/img/greece/flag_greece.png', 'Grèce', 'Greece');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GRL', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Groenland', 'Greenland');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GRD', 'https://mappi.net/country/img/grenada/flag_grenada.png', 'Grenade', 'Grenada');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GLP', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Guadeloupe', 'Guadeloupe');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GUM', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Guam', 'Guam');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GTM', 'https://mappi.net/country/img/guatemala/flag_guatemala.png', 'Guatémala', 'Guatemala');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GGY', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Guernesey', 'Guernsey');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GIN', 'https://mappi.net/country/img/guinea/flag_guinea.png', 'Guinée', 'Guinea');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GNB', 'https://mappi.net/country/img/guinea_bissau/flag_guinea_bissau.png', 'Guinée-Bissau', 'Guinea-Bissau');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GUY', 'https://mappi.net/country/img/guyana/flag_guyana.png', 'Guyane', 'Guyana');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('HTI', 'https://mappi.net/country/img/haiti/flag_haiti.png', 'Haïti', 'Haiti');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('HMD', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Heard et îles MacDonald', 'Heard Island and McDonald Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('HND', 'https://mappi.net/country/img/honduras/flag_honduras.png', 'Honduras', 'Honduras');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('HKG', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Hong Kong', 'Hong Kong');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('HUN', 'https://mappi.net/country/img/hungary/flag_hungary.png', 'Hongrie', 'Hungary');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ISL', 'https://mappi.net/country/img/iceland/flag_iceland.png', 'Islande', 'Iceland');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('IND', 'https://mappi.net/country/img/india/flag_india.png', 'Inde', 'India');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('IDN', 'https://mappi.net/country/img/indonesia/flag_indonesia.png', 'Indonésie', 'Indonesia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('IRN', 'https://mappi.net/country/img/iran/flag_iran.png', 'Iran', 'Iran');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('IRQ', 'https://mappi.net/country/img/iraq/flag_iraq.png', 'Irak', 'Iraq');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('IRL', 'https://mappi.net/country/img/ireland/flag_ireland.png', 'Irlande', 'Ireland');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('IMN', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Île de Man', 'Isle of Man');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ISR', 'https://mappi.net/country/img/israel/flag_israel.png', 'Israël', 'Israel');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ITA', 'https://mappi.net/country/img/italy/flag_italy.png', 'Italie', 'Italy');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CIV', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Côte-d''Ivoire', 'Ivory Coast');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('JAM', 'https://mappi.net/country/img/jamaica/flag_jamaica.png', 'Jamaïque', 'Jamaica');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('JPN', 'https://mappi.net/country/img/japan/flag_japan.png', 'Japon', 'Japan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('JEY', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Jersey', 'Jersey');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('JOR', 'https://mappi.net/country/img/jordan/flag_jordan.png', 'Jordanie', 'Jordan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KAZ', 'https://mappi.net/country/img/kazakhstan/flag_kazakhstan.png', 'Kazakhstan', 'Kazakhstan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KEN', 'https://mappi.net/country/img/kenya/flag_kenya.png', 'Kenya', 'Kenya');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KIR', 'https://mappi.net/country/img/kiribati/flag_kiribati.png', 'Kiribati', 'Kiribati');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('XKX', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Kosovo', 'Kosovo');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KWT', 'https://mappi.net/country/img/kuwait/flag_kuwait.png', 'Koweït', 'Kuwait');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KGZ', 'https://mappi.net/country/img/kyrgyzstan/flag_kyrgyzstan.png', 'Kirghizistan', 'Kyrgyzstan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LAO', 'https://mappi.net/country/img/laos/flag_laos.png', 'Laos', 'Laos');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LVA', 'https://mappi.net/country/img/latvia/flag_latvia.png', 'Lettonie', 'Latvia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LBN', 'https://mappi.net/country/img/lebanon/flag_lebanon.png', 'Liban', 'Lebanon');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LSO', 'https://mappi.net/country/img/lesotho/flag_lesotho.png', 'Lesotho', 'Lesotho');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LBR', 'https://mappi.net/country/img/liberia/flag_liberia.png', 'Libéria', 'Liberia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LBY', 'https://mappi.net/country/img/libya/flag_libya.png', 'Libye', 'Libya');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LIE', 'https://mappi.net/country/img/liechtenstein/flag_liechtenstein.png', 'Liechtenstein', 'Liechtenstein');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LTU', 'https://mappi.net/country/img/lithuania/flag_lithuania.png', 'Lituanie', 'Lithuania');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LUX', 'https://mappi.net/country/img/luxembourg/flag_luxembourg.png', 'Luxembourg', 'Luxembourg');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MAC', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Macao', 'Macao');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MDG', 'https://mappi.net/country/img/madagascar/flag_madagascar.png', 'Madagascar', 'Madagascar');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MWI', 'https://mappi.net/country/img/malawi/flag_malawi.png', 'Malawi', 'Malawi');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MYS', 'https://mappi.net/country/img/malaysia/flag_malaysia.png', 'Malaysie', 'Malaysia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MDV', 'https://mappi.net/country/img/maldives/flag_maldives.png', 'Maldives', 'Maldives');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MLI', 'https://mappi.net/country/img/mali/flag_mali.png', 'Mali', 'Mali');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MLT', 'https://mappi.net/country/img/malta/flag_malta.png', 'Malte', 'Malta');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MHL', 'https://mappi.net/country/img/marshall_islands/flag_marshall_islands.png', 'Îles Marshall', 'Marshall Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MTQ', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Martinique', 'Martinique');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MRT', 'https://mappi.net/country/img/mauritania/flag_mauritania.png', 'Mauritanie', 'Mauritania');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MUS', 'https://mappi.net/country/img/mauritius/flag_mauritius.png', 'Île Maurice', 'Mauritius');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MYT', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Mayotte', 'Mayotte');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MEX', 'https://mappi.net/country/img/mexico/flag_mexico.png', 'Mexique', 'Mexico');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('FSM', 'https://mappi.net/country/img/micronesia/flag_micronesia.png', 'Micronésie', 'Micronesia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MDA', 'https://mappi.net/country/img/moldova/flag_moldova.png', 'Moldavie', 'Moldova');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MCO', 'https://mappi.net/country/img/monaco/flag_monaco.png', 'Monaco', 'Monaco');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MNG', 'https://mappi.net/country/img/mongolia/flag_mongolia.png', 'Mongolie', 'Mongolia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MNE', 'https://mappi.net/country/img/montenegro/flag_montenegro.png', 'Monténégro', 'Montenegro');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MSR', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Montserrat', 'Montserrat');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MAR', 'https://mappi.net/country/img/morocco/flag_morocco.png', 'Maroc', 'Morocco');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MOZ', 'https://mappi.net/country/img/mozambique/flag_mozambique.png', 'Mozambique', 'Mozambique');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MMR', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Myanmar', 'Myanmar');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NAM', 'https://mappi.net/country/img/namibia/flag_namibia.png', 'Namibie', 'Namibia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NRU', 'https://mappi.net/country/img/nauru/flag_nauru.png', 'Nauru', 'Nauru');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NPL', 'https://mappi.net/country/img/nepal/flag_nepal.png', 'Népal', 'Nepal');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ANT', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Antilles néerlandaises', 'Netherlands Antilles');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NCL', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Nouvelle-Calédonie', 'New Caledonia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NZL', 'https://mappi.net/country/img/new_zealand/flag_new_zealand.png', 'Nouvelle Zélande', 'New Zealand');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NIC', 'https://mappi.net/country/img/nicaragua/flag_nicaragua.png', 'Nicaragua', 'Nicaragua');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NER', 'https://mappi.net/country/img/niger/flag_niger.png', 'Niger', 'Niger');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NGA', 'https://mappi.net/country/img/nigeria/flag_nigeria.png', 'Nigéria', 'Nigeria');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NIU', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Niue', 'Niue');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NFK', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Île Norfolk', 'Norfolk Island');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PRK', 'https://mappi.net/country/img/north_korea/flag_north_korea.png', 'Corée du Nord', 'North Korea');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MKD', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'North Macedonia', 'North Macedonia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MNP', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Mariannes du Nord', 'Northern Mariana Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NOR', 'https://mappi.net/country/img/norway/flag_norway.png', 'Norvège', 'Norway');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('OMN', 'https://mappi.net/country/img/oman/flag_oman.png', 'Oman', 'Oman');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PAK', 'https://mappi.net/country/img/pakistan/flag_pakistan.png', 'Pakistan', 'Pakistan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PLW', 'https://mappi.net/country/img/palau/flag_palau.png', 'Palaos', 'Palau');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PSE', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Territoire Palestinien', 'Palestinian Territory');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PAN', 'https://mappi.net/country/img/panama/flag_panama.png', 'Panama', 'Panama');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PNG', 'https://mappi.net/country/img/papua_new_guinea/flag_papua_new_guinea.png', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PRY', 'https://mappi.net/country/img/paraguay/flag_paraguay.png', 'Paraguay', 'Paraguay');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PER', 'https://mappi.net/country/img/peru/flag_peru.png', 'Pérou', 'Peru');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PHL', 'https://mappi.net/country/img/philippines/flag_philippines.png', 'Philippines', 'Philippines');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PCN', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Pitcairn', 'Pitcairn');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('POL', 'https://mappi.net/country/img/poland/flag_poland.png', 'Pologne', 'Poland');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PRT', 'https://mappi.net/country/img/portugal/flag_portugal.png', 'Portugal', 'Portugal');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('PRI', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Puerto Rico', 'Puerto Rico');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('QAT', 'https://mappi.net/country/img/qatar/flag_qatar.png', 'Qatar', 'Qatar');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('COG', 'https://mappi.net/country/img/congo/flag_congo.png', 'République du Congo', 'Republic of the Congo');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('REU', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'La Réunion', 'Reunion');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ROU', 'https://mappi.net/country/img/romania/flag_romania.png', 'Roumanie', 'Romania');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('RUS', 'https://mappi.net/country/img/russia/flag_russia.png', 'Russie', 'Russia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('RWA', 'https://mappi.net/country/img/rwanda/flag_rwanda.png', 'Rwanda', 'Rwanda');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('BLM', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Saint Barthélemy', 'Saint Barthelemy');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SHN', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Sainte-Hélène', 'Saint Helena');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KNA', 'https://mappi.net/country/img/saint_kitts_and_nevis/flag_saint_kitts_and_nevis.png', 'Saint-Kitts-et-Nevis', 'Saint Kitts and Nevis');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LCA', 'https://mappi.net/country/img/saint_lucia/flag_saint_lucia.png', 'Sainte-Lucie', 'Saint Lucia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('MAF', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Saint-Martin', 'Saint Martin');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SPM', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Saint Pierre et Miquelon', 'Saint Pierre and Miquelon');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('VCT', 'https://mappi.net/country/img/saint_vincent_and_the_grenadines/flag_saint_vincent_and_the_grenadines.png', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('WSM', 'https://mappi.net/country/img/samoa/flag_samoa.png', 'Samoa', 'Samoa');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SMR', 'https://mappi.net/country/img/san_marino/flag_san_marino.png', 'San Marin', 'San Marino');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('STP', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Sao Tomé-et-Principe', 'Sao Tome and Principe');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SAU', 'https://mappi.net/country/img/saudi_arabia/flag_saudi_arabia.png', 'Arabie Saoudite', 'Saudi Arabia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SEN', 'https://mappi.net/country/img/senegal/flag_senegal.png', 'Sénégal', 'Senegal');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SRB', 'https://mappi.net/country/img/serbia/flag_serbia.png', 'Serbie', 'Serbia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SCG', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Serbie et Montenegro', 'Serbia and Montenegro');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SYC', 'https://mappi.net/country/img/seychelles/flag_seychelles.png', 'Seychelles', 'Seychelles');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SLE', 'https://mappi.net/country/img/sierra_leone/flag_sierra_leone.png', 'Sierra Leone', 'Sierra Leone');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SGP', 'https://mappi.net/country/img/singapore/flag_singapore.png', 'Singapour', 'Singapore');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SXM', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Saint-Martin', 'Sint Maarten');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SVK', 'https://mappi.net/country/img/slovakia/flag_slovakia.png', 'Slovaquie', 'Slovakia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SVN', 'https://mappi.net/country/img/slovenia/flag_slovenia.png', 'Slovénie', 'Slovenia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SLB', 'https://mappi.net/country/img/solomon_islands/flag_solomon_islands.png', 'Îles Salomon', 'Solomon Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SOM', 'https://mappi.net/country/img/somalia/flag_somalia.png', 'Somalie', 'Somalia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ZAF', 'https://mappi.net/country/img/south_africa/flag_south_africa.png', 'Afrique du Sud', 'South Africa');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SGS', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Géorgie du Sud et les îles Sandwich', 'South Georgia and the South Sandwich Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('KOR', 'https://mappi.net/country/img/south_korea/flag_south_korea.png', 'Corée du Sud', 'South Korea');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SSD', 'https://mappi.net/country/img/south_sudan/flag_south_sudan.png', 'Soudan du Sud', 'South Sudan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ESP', 'https://mappi.net/country/img/spain/flag_spain.png', 'Espagne', 'Spain');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('LKA', 'https://mappi.net/country/img/sri_lanka/flag_sri_lanka.png', 'Sri Lanka', 'Sri Lanka');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SDN', 'https://mappi.net/country/img/sudan/flag_sudan.png', 'Soudan', 'Sudan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SUR', 'https://mappi.net/country/img/suriname/flag_suriname.png', 'Surinam', 'Suriname');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SJM', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Svalbard et Jan Mayen', 'Svalbard and Jan Mayen');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SWE', 'https://mappi.net/country/img/sweden/flag_sweden.png', 'Suède', 'Sweden');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('CHE', 'https://mappi.net/country/img/switzerland/flag_switzerland.png', 'Suisse', 'Switzerland');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('SYR', 'https://mappi.net/country/img/syria/flag_syria.png', 'Syrie', 'Syria');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TWN', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Taiwan', 'Taiwan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TJK', 'https://mappi.net/country/img/tajikistan/flag_tajikistan.png', 'Tajikistan', 'Tajikistan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TZA', 'https://mappi.net/country/img/tanzania/flag_tanzania.png', 'Tanzanie', 'Tanzania');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('THA', 'https://mappi.net/country/img/thailand/flag_thailand.png', 'Thaïlande', 'Thailand');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('NLD', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'The Netherlands', 'The Netherlands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TLS', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Timor Leste', 'Timor Leste');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TGO', 'https://mappi.net/country/img/togo/flag_togo.png', 'Togo', 'Togo');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TKL', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Tokelau', 'Tokelau');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TON', 'https://mappi.net/country/img/tonga/flag_tonga.png', 'Tonga', 'Tonga');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TTO', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Trinité et Tobago', 'Trinidad and Tobago');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TUN', 'https://mappi.net/country/img/tunisia/flag_tunisia.png', 'Tunisie', 'Tunisia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TUR', 'https://mappi.net/country/img/turkey/flag_turkey.png', 'Turquie', 'Turkey');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TKM', 'https://mappi.net/country/img/turkmenistan/flag_turkmenistan.png', 'Turkménistan', 'Turkmenistan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TCA', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Turques et Caïques', 'Turks and Caicos Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('TUV', 'https://mappi.net/country/img/tuvalu/flag_tuvalu.png', 'Tuvalu', 'Tuvalu');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('VIR', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Vierges des États-Unis', 'U.S. Virgin Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('UGA', 'https://mappi.net/country/img/uganda/flag_uganda.png', 'Ouganda', 'Uganda');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('UKR', 'https://mappi.net/country/img/ukraine/flag_ukraine.png', 'Ukraine', 'Ukraine');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ARE', 'https://mappi.net/country/img/united_arab_emirates/flag_united_arab_emirates.png', 'Émirats Arabes Unis', 'United Arab Emirates');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('GBR', 'https://mappi.net/country/img/united_kingdom/flag_united_kingdom.png', 'Royaume-Uni', 'United Kingdom');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('USA', 'https://mappi.net/country/img/united_states/flag_united_states.png', 'États-Unis ', 'United States');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('UMI', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Îles Mineures éloignées des États-Unis', 'United States Minor Outlying Islands');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('URY', 'https://mappi.net/country/img/uruguay/flag_uruguay.png', 'Uruguay', 'Uruguay');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('UZB', 'https://mappi.net/country/img/uzbekistan/flag_uzbekistan.png', 'Ouzbékistan', 'Uzbekistan');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('VUT', 'https://mappi.net/country/img/vanuatu/flag_vanuatu.png', 'Vanuatu', 'Vanuatu');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('VAT', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Vatican', 'Vatican');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('VEN', 'https://mappi.net/country/img/venezuela/flag_venezuela.png', 'Vénézuela', 'Venezuela');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('VNM', 'https://mappi.net/country/img/viet_nam/flag_viet_nam.png', 'Vietnam', 'Vietnam');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('WLF', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Wallis et Futuna', 'Wallis and Futuna');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ESH', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Olympic_flag.svg', 'Sahara occidental', 'Western Sahara');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('YEM', 'https://mappi.net/country/img/yemen/flag_yemen.png', 'Yemen', 'Yemen');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ZMB', 'https://mappi.net/country/img/zambia/flag_zambia.png', 'Zambie', 'Zambia');
INSERT INTO Pays(ID, Drapeau, Nom_Francais, Nom_Anglais) VALUES ('ZWE', 'https://mappi.net/country/img/zimbabwe/flag_zimbabwe.png', 'Zimbabwe', 'Zimbabwe');
