INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75008,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75007,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75016,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('uvea',98600,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('villepinte',93420,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('puteaux',92800,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('vaires sur marne',77360,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75018,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75011,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('boulogne billancourt',92100,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('nantes',44100,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('decines charpieu',69150,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('vanves',92170,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('st priest en jarez',42270,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75015,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('bassens',33530,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('st denis',93200,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('elancourt',78990,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('lezennes',59260,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('st laurent du var',06700,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('marseille',13007,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('colombes',92700,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('le bourget',93350,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('guyancourt',78280,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('montigny le bretonneux',78180,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('bailly',78870,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('etrechet',36120,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75004,NULL);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('marseille',13005,NULL);
