INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75008,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75007,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75016,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('uvea',98600,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('villepinte',93420,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('puteaux',92800,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('vaires sur marne',77360,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75018,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75011,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('boulogne billancourt',92100,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('nantes',44100,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('decines charpieu',69150,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('vanves',92170,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('st priest en jarez',42270,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75015,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('bassens',33530,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('st denis',93200,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('elancourt',78990,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('lezennes',59260,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('st laurent du var',06700,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('marseille',13007,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('colombes',92700,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('le bourget',93350,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('guyancourt',78280,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('montigny le bretonneux',78180,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('bailly',78870,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('etrechet',36120,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('paris',75004,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES('marseille',13005,None);
