/* sitessql.txt */
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.86616355, 2.3125474, 'Grand Palais', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.8531, 2.30252, 'Arena Champ de Mars', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.845968, 2.253522, 'Stade Roland Garros', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (-17.86693, -149.25208, 'Tahiti Teahupo'o', None, None, None, 'uvea');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.9721, 2.5149, 'Arena Paris Nord', None, None, None, 'villepinte');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.8954, 2.2294, 'Paris La Défense Arena', None, None, None, 'puteaux');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.8623, 2.6348, 'Stade nautique de Vaires-sur-Marne', None, None, None, 'vaires sur marne');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.8997292, 2.3605141, 'Arena Porte de la Chapelle', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.83863, 2.378597, 'Arena Bercy', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.84156974, 2.253048697, 'Parc des Princes', None, None, None, 'boulogne billancourt');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (47.25593494, -1.52469927, 'Stade de la Beaujoire', None, None, None, 'nantes');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (45.76514165, 4.98199275, 'Stade de Lyon', None, None, None, 'decines charpieu');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.8637, 2.3134, 'Pont Alexandre III', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.832968, 2.2840069, 'Arena Paris Sud 1', None, None, None, 'vanves');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (45.4607, 4.3902, 'Stade Geoffroy-Guichard', None, None, None, 'st priest en jarez');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.85972558, 2.29221884, 'Trocadéro', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.85613, 2.2978, 'Stade Tour Eiffel', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (44.8974, -0.5616, 'Stade de Bordeaux', None, None, None, 'bassens');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.830184, 2.289033, 'Arena Paris Sud 4', None, None, None, 'vanves');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.924475, 2.360127, 'Stade de France', None, None, None, 'st denis');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.78981063, 1.9642379, 'Colline d’Elancourt', None, None, None, 'elancourt');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (50.61190661, 3.13047318, 'Stade Pierre Mauroy', None, None, None, 'lezennes');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (43.7051, 7.1926, 'Stade de Nice', None, None, None, 'st laurent du var');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (43.2661, 5.3678, 'Marina de Marseille', None, None, None, 'marseille');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.829381, 2.290865, 'Arena Paris Sud 6', None, None, None, 'vanves');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.92934371, 2.24777122, 'Stade Yves-du-Manoir', None, None, None, 'colombes');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.93693402, 2.41997931, 'Site d’escalade du Bourget', None, None, None, 'le bourget');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.7532, 2.0758, 'Golf National', None, None, None, 'guyancourt');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.78800979, 2.03498269, 'Vélodrome National de Saint-Quentin-en-Yvelines', None, None, None, 'montigny le bretonneux');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.81432266, 2.08452588, 'Château de Versailles', None, None, None, 'bailly');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.85704803, 2.312835932, 'Invalides', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (46.8157, 1.7582, 'Centre national de tir de Châteauroux', None, None, None, 'etrechet');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.86640642, 2.32119515, 'La Concorde 1', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.86504456, 2.32119516, 'La Concorde 2', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.86486788, 2.32139191, 'La Concorde 3', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.86573765, 2.3220383, 'La Concorde 4', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.8563881, 2.35222203, 'Hôtel de Ville', None, None, None, 'paris');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (48.923723, 2.35578, 'Centre Aquatique', None, None, None, 'st denis');
INSERT INTO Sites(Latitude_Sites, Longitude_Sites, Nom_Sites, Date_de_construction_Sites, Capacite_d_acceuil_Sites, Accessibilite_Sites, Nom_Villes) VALUES (43.2698, 5.3959, 'Stade de Marseille', None, None, None, 'marseille');

/* villessql.txt */
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(paris,75008,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(paris,75007,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(paris,75016,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(uvea,98600,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(villepinte,93420,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(puteaux,92800,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(vaires sur marne,77360,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(paris,75018,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(paris,75011,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(boulogne billancourt,92100,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(nantes,44100,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(decines charpieu,69150,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(vanves,92170,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(st priest en jarez,42270,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(paris,75015,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(bassens,33530,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(st denis,93200,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(elancourt,78990,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(lezennes,59260,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(st laurent du var,06700,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(marseille,13007,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(colombes,92700,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(le bourget,93350,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(guyancourt,78280,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(montigny le bretonneux,78180,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(bailly,78870,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(etrechet,36120,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(paris,75004,None);
INSERT INTO Villes(Nom_Villes, Code_Postal_Villes, Population_Villes) VALUES(marseille,13005,None);

