name: Generate SQL Files

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  generate_file:
    name: Generate SQL Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1' 

    - name: Run Python script
      run: python SQL/concat.py

    - name: Check changes
      run: |
        git diff --exit-code --quiet || echo "No changes to commit"

    - name: Commit changes
      if: ${{ !cancelled() }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add SQL generated file" || echo "No changes to commit"
        git push
