name: Generate SQL Files

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  generate_file:
    name: Generate SQL Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1' 
    
    - name: Install dependencies
      run: pip install mysql-connector-python

    - name: Generate SQL Files
      run: python SQL/concat.py
      
    - name: Upload to Server
      run: python Auto/ftp_deploiement.py "${{ secrets.FTP_USERNAME }}" "${{ secrets.FTP_PASSWORD }}"
      
    - name: Check changes
      run: |
        git diff --exit-code --quiet || echo "No changes to commit"

    - name: Commit changes
      if: ${{ !cancelled() }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add SQL generated file" || echo "No changes to commit"
        git push
        
    - name: Update Database
      run: |
        cd SQL/Group/
        for file in *.sql; do  # Loop through all SQL files in the directory
          echo "Executing SQL file: $file"
          mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USERNAME }} -p"${{ secrets.DB_PASSWORD }}" ${{ secrets.DB_NAME }} < "$file"
        done
