INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("FEN","Escrime","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("TKW","Taekwondo","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("JUD","Judo","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("WRE","Lutte","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("TEN","Tennis","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BOX","Boxe","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SRF","Surf","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("JUD_PARA","Para Judo","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("WRU_PARA","Rugby fauteuil","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("VBS_PARA","Volleyball assis","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SWM_PARA","Para Natation","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("ROW_PARA","Para Aviron","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CSP_PARA","Para Canoë","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BDM","Badminton","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("GRY","Gymnastique rythmique","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BKB","Basketball","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("GAR","Gymnastique artistique","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("GTR","Gymnastique trampoline","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("FBL","Football","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("TRI_PARA","Para Triathlon","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("VVO","Volley-ball","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("MDN","Pentathlon moderne","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("ROW","Aviron","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CSP","Canoë-kayak sprint","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("ATH_PARA","Athlétisme","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CRD_PARA","Cyclisme sur route - course sur route","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("FBB_PARA","Cécifoot","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("TTE","Tennis de table","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("ATH","Athlétisme","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("RU7","Rugby à 7","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("MTB","Cycling Mountain Bike","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("HBL","Handball","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SAL","Voile","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("TTE_PARA","Tennis de table para","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("WLF","Haltérophilie","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("VBV","Volley-ball de plage","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CRD","Cyclisme sur route - Course sur route","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("HOC","Hockey","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BDM_PARA","Para badminton","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("PWL_PARA","Para Haltérophilie","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("GBL_PARA","Goalball","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CLB","Escalade","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("GLF","Golf","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CTR_PARA","Para Cyclisme sur piste","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("EDR","Sports équestres - dressage","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("EVE","Sports équestres - concours complet","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("EJP","Sports équestres - saut d'obstacles","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("MPN","Pentathlon moderne","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CTR","Cyclisme sur piste","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("EQU_PARA","Para Equitation","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("ARC","Tir à l'arc","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SWM","Natation","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("WPO","Water-polo","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BMX","BMX Racing","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SHO","Tir","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SHO_PARA","Para Tir Sportif","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BK3","Basketball 3x3","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BKG","Breaking","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BMF","BMX freestyle","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SKB","Skateboard - Street","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("OWS","Natation marathon","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("TRI","Triathlon","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("SWA","Natation artistique","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("DIV","Plongeon","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("CSL","Canoë-kayak slalom","olympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("WFE_PARA","Escrime fauteuil","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("TKW_PARA","Para Taekwondo","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("WTE_PARA","Tennis fauteuil","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("ARC_PARA","Para Tir à l'arc","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("BOC_PARA","Boccia","paralympic","logo"),
INSERT INTO Epreuves(ID_Epreuves, Nom_Epreuves, Catégorie_Epreuves, Logo_Epreuves) VALUES ("WBK_PARA","Basketball fauteuil","paralympic","logo"),


